import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Box from '@mui/material/Box'
import Grid from '@mui/material/Grid'
import PetsIcon from '@mui/icons-material/Pets'
import { makeStyles } from '@material-ui/styles'


const useStyles = makeStyles({
  navbar: {
    borderBottom: '1px solid black'
  }
})

const Home: NextPage = () => {

  const styles = useStyles();

  return (
    <div>
      <Head>
        <title>Share Peis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <Box className={styles.navbar}>
        <PetsIcon />
      </Box>

    </div>
  )
}

export default Home
