import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Box from '@mui/material/Box'
import Grid from '@mui/material/Grid'
import PetsIcon from '@mui/icons-material/Pets'
import { makeStyles } from '@material-ui/styles'
import { blueGrey, blue } from '@mui/material/colors'
import { Button, Card, CardMedia, Typography } from '@mui/material'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import CircularProgress from '@mui/material/CircularProgress'
import axios from 'axios'


export interface Response {
  data: Data[]
}

export interface Data {
  breeds: Breed[];
  id: string;
  url: string;
  width: number;
  height: number;
}

export interface Breed {
  weight: Metrics;
  height: Metrics;
  id: number;
  name: string;
  bred_for: string;
  breed_group: string;
  life_span: string;
  temperament: string;
  reference_image_id: string;
}

export interface Metrics {
  imperial: string;
  metric: string;
}


const useStyles = makeStyles({
  navbar: {
    height: '10vh',
    padding: 10,
    borderBottom: '1px solid',
    borderBottomColor: blueGrey[100],
    display: 'flex',
    alignItems: 'center',
    gap: 10,
    color: blueGrey[700]
  },
  logo: {
    color: blueGrey[300],
    '&:hover': {
      color: blueGrey[500]
    }
  },
  main: {
    height: '85vh',
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center'
  },
  container: {
    width: '50%',
    height: 'fit-content',
    maxHeight: 700,
    minWidth: 250,
    padding: 10
  },
  footer: {
    height: '5vh',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 5
  },
  github: {
    color: blue[300],
    cursor: 'pointer',
    '&:hover': {
      textDecoration: 'underline'
    }
  }
})

const Home: NextPage = () => {

  const styles = useStyles();
  const [imgUrl, setImgUrl] = useState('');
  const [height, setHeight] = useState(0);
  const [width, setWidth] = useState(0);

  useEffect(() => {
    async function fetch() {
      const response: Response = await axios.get('https://api.thedogapi.com/v1/images/search?limit=1')
      setImgUrl(response.data[0].url)
      setHeight(response.data[0].height)
      setWidth(response.data[0].width)
    }
    fetch();

  }, [])

  const newDog = async () => {
    setImgUrl('')
    const response: Response = await axios.get('https://api.thedogapi.com/v1/images/search?limit=1')
    setImgUrl(response.data[0].url)
    setHeight(response.data[0].height)
    setWidth(response.data[0].width)
  }

  return (
    <div>
      <Head>
        <title>Share Peis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <Box className={styles.navbar}>
        <PetsIcon className={styles.logo} fontSize={'large'} />
        <Typography variant="h4" component="p">
          Share Peis
        </Typography>
      </Box>
      <Box className={styles.main}>
        <Card className={styles.container}>
          <Grid container >
            <Grid item container flexDirection='column'>
              <Typography style={{
                fontWeight: 800
              }}>
                Breed:
            </Typography>
              <Typography
                style={{
                  fontWeight: 300
                }}>
                Shar Pei
            </Typography>
            </Grid>
            {imgUrl ?
              <>
                <CardMedia
                  component='img'
                  height={400}
                  width={width}
                  image={imgUrl} />
                <Button onClick={newDog} style={{
                  marginTop: 10
                }}>New Dog</Button>
              </>
              :
              <Box style={{
                width: '100%',
                display: 'flex',
                justifyContent: 'center'
              }}>
                <CircularProgress style={{ color: blueGrey[300] }} />
              </Box>
            }

          </Grid>
        </Card>
      </Box>
      <Box className={styles.footer}>
        Developed by
        <Link href="https://github.com/lmhmDev" passHref={true}>
          <Typography className={styles.github}>
            Lorenzo Hermoso
          </Typography>
        </Link>
      </Box>
    </div>
  )
}

export default Home
